title: anverso
description: Pequena coleção de poesia

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-tagories

skin: sunrise
destination: ../anverso-deploy

collections:
  authors:
    output: true
  poems:
    output: true

pagination:
  
  enabled: true
  debug: false
  collection: 'poems'
  per_page: 10
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  title: ':title - página :num de :max'

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "poems"
    values:
      layout: "poem"

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
  - "*.bak"
  - "**/*.bak"
  - .gitignore

# Jekyll SEO Tag (Optional)
# =========================